### ISSUE TITLE
RuntimeError: Given input size: (512x2x3). Calculated output size: (512x0x0). Output size is too small

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [bradleybin/Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD#1]
I get an Error when executing your Testexample:

`python main_joint.py --mode test --clm_model ./model/joint/clm_final.pth  --fsm_model ./model/joint/fsm_final.pth --test_fold ./testRes --sal_mode t`

I am running Windows 10 with Cuda 10.1 and Torch 1.7.1

```
Traceback (most recent call last):
  File "main_joint.py", line 282, in <module>
    main(config)
  File "main_joint.py", line 229, in main
    test.test()
  File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\Solver_joint.py", line 84, in test
    feasum_out, merge_solid, out_merge_solid1, out_merge_solid2, out_merge_solid3, out_merge_solid4 = self.net(images)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\KRN.py", line 155, in forward
    merge_solid1 = self.DeepPool_solid1(conv2merge[0], conv2merge[1])
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\KRN.py", line 54, in forward
    y = self.convs[i](self.pools[i](y))
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\pooling.py", line 594, in forward
    return F.avg_pool2d(input, self.kernel_size, self.stride,
RuntimeError: Given input size: (512x2x3). Calculated output size: (512x0x0). Output size is too small
```

**Comment by bradleybin** [comment]
I guess the size of your input image is too small.  The size of most training and testing images is larger than 200x200.

**Comment by Sebastian-Schuchmann** [comment]
I am using the DUTS-TE Dataset for testing like in your example, shouldn't that work? Looking at the sizes they all seems to be around 300x400 Pixel

**Comment by bradleybin** [comment]
Yes, the images in the DUTS-TE dataset can work. But I haven't encountered such a problem. I will check our code again.

**Comment by Sebastian-Schuchmann** [comment]
Switching the Images with higher resolution one seems to solve the issue, sadly my GPU seems to be to low on Memory.

I get the following Error
`RuntimeError: CUDA out of memory. Tried to allocate 264.00 MiB (GPU 0; 6.00 GiB total capacity; 4.18 GiB already allocated; 0 bytes free; 4.57 GiB reserved in total by PyTorch)`

Is there a minimum requirement?

**Comment by user-wu** [comment]
> I get an Error when executing your Testexample:
> 
> `python main_joint.py --mode test --clm_model ./model/joint/clm_final.pth --fsm_model ./model/joint/fsm_final.pth --test_fold ./testRes --sal_mode t`
> 
> I am running Windows 10 with Cuda 10.1 and Torch 1.7.1
> 
> ```
> Traceback (most recent call last):
>   File "main_joint.py", line 282, in <module>
>     main(config)
>   File "main_joint.py", line 229, in main
>     test.test()
>   File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\Solver_joint.py", line 84, in test
>     feasum_out, merge_solid, out_merge_solid1, out_merge_solid2, out_merge_solid3, out_merge_solid4 = self.net(images)
>   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\KRN.py", line 155, in forward
>     merge_solid1 = self.DeepPool_solid1(conv2merge[0], conv2merge[1])
>   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\KRN.py", line 54, in forward
>     y = self.convs[i](self.pools[i](y))
>   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\pooling.py", line 594, in forward
>     return F.avg_pool2d(input, self.kernel_size, self.stride,
> RuntimeError: Given input size: (512x2x3). Calculated output size: (512x0x0). Output size is too small
> ```

I encountered the same problem, have you solved it?

**Comment by bradleybin** [comment]
> Switching the Images with higher resolution one seems to solve the issue, sadly my GPU seems to be to low on Memory.
> 
> I get the following Error
> `RuntimeError: CUDA out of memory. Tried to allocate 264.00 MiB (GPU 0; 6.00 GiB total capacity; 4.18 GiB already allocated; 0 bytes free; 4.57 GiB reserved in total by PyTorch)`
> 
> Is there a minimum requirement?

NVIDIA 2080Ti with 11G can work.

**Comment by bradleybin** [comment]
> > I get an Error when executing your Testexample:
> > `python main_joint.py --mode test --clm_model ./model/joint/clm_final.pth --fsm_model ./model/joint/fsm_final.pth --test_fold ./testRes --sal_mode t`
> > I am running Windows 10 with Cuda 10.1 and Torch 1.7.1
> > ```
> > Traceback (most recent call last):
> >   File "main_joint.py", line 282, in <module>
> >     main(config)
> >   File "main_joint.py", line 229, in main
> >     test.test()
> >   File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\Solver_joint.py", line 84, in test
> >     feasum_out, merge_solid, out_merge_solid1, out_merge_solid2, out_merge_solid3, out_merge_solid4 = self.net(images)
> >   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
> >     result = self.forward(*input, **kwargs)
> >   File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\KRN.py", line 155, in forward
> >     merge_solid1 = self.DeepPool_solid1(conv2merge[0], conv2merge[1])
> >   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
> >     result = self.forward(*input, **kwargs)
> >   File "C:\Users\Seppi\Desktop\MobulaOP\Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD\KRN.py", line 54, in forward
> >     y = self.convs[i](self.pools[i](y))
> >   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
> >     result = self.forward(*input, **kwargs)
> >   File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\pooling.py", line 594, in forward
> >     return F.avg_pool2d(input, self.kernel_size, self.stride,
> > RuntimeError: Given input size: (512x2x3). Calculated output size: (512x0x0). Output size is too small
> > ```
> 
> I encountered the same problem, have you solved it?

Could you print the shape and path of your input image? Make sure they are right.

**Comment by YAOSL98** [comment]
I change datasets, and train these code, also have this problem!

**Comment by bradleybin** [comment]
I re-tested the code and I think I may have found the problem. I encountered the same problem "RuntimeError: Given input size: (512x2x3). Calculated output size: (512x0x0). Output size is too small" with Pytorch 1.6.0, but it can work with **Pytorch 1.0.0**. 
Using a high version of Pytorch may cause this problem, so try a lower version.

**Comment by clelouch** [comment]
It seems the DeepPoolLayer_first is similar to the fam in poolnet. In the forward process of the DeepPoolLayer_first, a feature map is subsampled by a factor of 2, 4, and 8, successively. However, in the original poolnet repo., the three subsampling operations are conducted separatedly, i.e. `y=self.convs[i](self.pools[i](x)).` Is it a typo?

**Comment by clelouch** [comment]
After rechecking the code and paper, I guess that the error is caused by a typo. The `  self.pools_sizes = [2, 4, 8]` should be  changed into`        self.pools_sizes = [2, 2, 2]`. However, after modifing the code, the genearetd results are still different from the provided saliency maps.
For example, these two results are slightly different.
![0016](https://user-images.githubusercontent.com/33519394/124286822-ea1d8780-db81-11eb-89d9-90520944c5d2.png)
(provided saliency map)

![0016](https://user-images.githubusercontent.com/33519394/124286738-d4a85d80-db81-11eb-8a95-6556a7d72647.png)
(generated saliency map)

**Comment by YAOSL98** [comment]
Thanks a lot, I will try your method!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bradleybin/Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 晚上10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bradleybin/Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD] RuntimeError: Given input size: (512x2x3). Calculated output size: (512x0x0). Output size is too small (#1)





 
After rechecking the code and paper, I believe that the error is caused by a typo. The   self.pools_sizes = [2, 4, 8] should be  changed into        self.pools_sizes = [2, 2, 2].

**Comment by bradleybin** [comment]
> After rechecking the code and paper, I guess that the error is caused by a typo. The ` self.pools_sizes = [2, 4, 8]` should be changed into` self.pools_sizes = [2, 2, 2]`. However, after modifing the code, the genearetd results are still different from the provided saliency maps.
> For example, these two results are slightly different.
> ![0016](https://user-images.githubusercontent.com/33519394/124286822-ea1d8780-db81-11eb-89d9-90520944c5d2.png)
> (provided saliency map)
> 
> ![0016](https://user-images.githubusercontent.com/33519394/124286738-d4a85d80-db81-11eb-8a95-6556a7d72647.png)
> (generated saliency map)

非常感谢你关注我们的工作并发现了我们代码中关键的错误。确实由于我们的粗心，这个地方出现了你说的问题，我们将会马上纠正这个错误。
我们提供的saliency maps和我们提供的训练好的模型出来的结果的确不一样。我们提供的预测saliency maps是我们论文中使用的那个版本（论文里的实验结果都是基于我们提供的这个显著性图），我们提供它也是为了方便接下来的工作和我们的工作比较。但是这个结果是我们比较早期训练出来的，所用的代码比较粗糙。为了方便大家更好理解我们的工作，我们就写了这个当前所公开的代码。不过，我们提供的训练好的模型测试结果出来的结果是近似甚至略好于我们提供的saliency maps。
另外，我们近期会基于纠正后的代码重新训练一遍，然后放上来的。
最后再次真心感谢发现我们代码的问题！如果有问题的话，欢迎一起交流探讨（xubinwei@zjut.edu.cn）

**Comment by clelouch** [comment]
您客气了，我也从您的论文和代码中受到了一些启发，感谢您能够公布自己的代码~
