### ISSUE TITLE
AttributeError: module 'mobula.op' has no attribute 'AttSamplerGrid'

### ISSUE THREAD

**Issue by yun-liu** [bradleybin/Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD#2]
Hi! I follow your instructions to install this software. When I run the code, I get this error:
```
File "/home/xxx/xxx/attention_sampler/attsampler_th.py", line 19, in forward
    grid = mobula.op.AttSamplerGrid(data.detach(),
AttributeError: module 'mobula.op' has no attribute 'AttSamplerGrid'
```
Can you kindly give me some suggestions? Any comments will be highly appreciately!

**Comment by yun-liu** [comment]
I have solved this problem. Thanks!

**Comment by clelouch** [comment]
I have the same problem. Could you please tell me how you solve this issue?
