### ISSUE TITLE
DUTS-TR-Edge

### ISSUE THREAD

**Issue by jiangyuanlin01** [bradleybin/Locate-Globally-Segment-locally-A-Progressive-Architecture-With-Knowledge-Review-Network-for-SOD#3]
DUTS-TR-Edge，How do I get this data set？

**Comment by bradleybin** [comment]
https://github.com/backseason/PoolNet

**Comment by bradleybin** [comment]
> DUTS-TR-Edge，How do I get this data set？

https://github.com/backseason/PoolNet
